# Copyright (c) 2018 Ruslan Variushkin,  ruslan@host4.biz
version = '0.0.6'

Help_desc = "ispcli works with ispmanager5 through API"
Hepl_epilog = "Thanks for using"
Help_user_list="list all of users"
Help_output = "Output the result to a file"
Help_user_name = "User name"
Help_user_domains = "Domains list"
Help_user_webdomains = "List of webdomains and their configurations"
Help_billing = "Billing information, users and emails"
Help_emails = "List of accounts' emails"
Help_dbs = "List of databases"
Help_dbs_users = "List of databases and users of databases"
Help_email_info = "Email settings"
Help_user = "Specify username"
Help_email = "List of setting of emails"
Help_user_get_email = "Get user's email"
Help_web_script_packages = "List of script packages, example --web_script_packages WordPress"
Help_web_scripts = "List of web-scripts"
Help_version = "Show version"
Help_insecure="Insecure connection, tls"